NUMBER_OF_CHANNELS = 32
CHANNEL_LENGTH = 18
SIGNAL_SIZE = NUMBER_OF_CHANNELS * CHANNEL_LENGTH

RECEIVE_FREQUENCY = 4

RECEIVE_CHUNK_SIZE = RECEIVE_FREQUENCY * SIGNAL_SIZE

SERVER_HOST = "localhost"
SERVER_PORT = 5000

BUFFER_LIMIT = 10000

SAMPLING_FREQUENCY = 1000
LOW_CUTOFF_FREQUENCY = 1.0
HIGH_CUTOFF_FREQUENCY = 100.0
RMS_WINDOW = 50
FILTER_ORDER = 4
